# Generated by Django 5.2.4 on 2025-08-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
